---
inline:
  query:
    bool:
      filter:
        exists:
          field: "ccni_number"
      must:
        function_score:
          query:
            dis_max:
              queries:
              - multi_match:
                  query: "{{name}}"
                  fields:
                  - known_as^3
                  - alt_names
              - match_phrase:
                  known_as: "{{name}}"
          functions:
          - filter:
              match_phrase_prefix:
                known_as: "{{name}}"
            weight: 200
          - filter:
              multi_match:
                query: "{{name}}"
                fields:
                - known_as^3
                - alt_names
                operator: and
            weight: 10
params:
  name: term
